name: Deploy to GCP Artifact Registry
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setting up GCP authentication..."
      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICEACC_KEY }}
      - run: echo "Successfully authenticated to GCP."
      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - run: echo "Docker is configured to use GCP Artifact Registry."
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t us-central1-docker.pkg.dev/upheld-welder-439421-m8/lab3-cs1660:latest ./cs1660-lab3
      - run: echo "Docker image built successfully."
      - name: Push Docker image
        run: |
          echo "Pushing Docker image to Artifact Registry..."
          docker push us-central1-docker.pkg.dev/upheld-welder-439421-m8/lab3-cs1660/my-app:latest
      - run: echo "Docker image pushed successfully to Artifact Registry."
